name: story_lab
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  intl: ^0.20.2
  fpdart:
  supabase_flutter: ^2.9.1
  fluttertoast: ^8.2.12
  flutter_svg: ^2.1.0
  url_launcher: ^6.3.1
  hugeicons: ^0.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/illustrations/